-- MySQL Script generated by MySQL Workbench
-- Fri 20 Sep 2019 10:35:28 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Office` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Person_id` INT NOT NULL,
  PRIMARY KEY (`Person_id`),
  CONSTRAINT `fk_Employee_Person`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employment` (
  `id` INT NOT NULL,
  `Employee_Person_id` INT NOT NULL,
  `Office_id` INT NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `salary` DOUBLE NOT NULL,
  `terminated` BIT NOT NULL,
  INDEX `fk_EmployeeWorkRecord_Employee1_idx` (`Employee_Person_id` ASC) VISIBLE,
  INDEX `fk_EmployeeWorkRecord_Office1_idx` (`Office_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `Employee_Person_id`, `Office_id`),
  CONSTRAINT `fk_EmployeeWorkRecord_Employee1`
    FOREIGN KEY (`Employee_Person_id`)
    REFERENCES `mydb`.`Employee` (`Person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmployeeWorkRecord_Office1`
    FOREIGN KEY (`Office_id`)
    REFERENCES `mydb`.`Office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Timesheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Timesheet` (
  `idTimesheet` INT NOT NULL,
  `EmploymentID` INT NOT NULL,
  `date_worked` DATETIME NOT NULL,
  `hours_worked` DOUBLE NOT NULL,
  PRIMARY KEY (`idTimesheet`, `EmploymentID`),
  INDEX `fk_Timesheet_Employment1_idx` (`EmploymentID` ASC) VISIBLE,
  CONSTRAINT `fk_Timesheet_Employment1`
    FOREIGN KEY (`EmploymentID`)
    REFERENCES `mydb`.`Employment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `Person_id` INT NOT NULL,
  INDEX `fk_Client_Person1_idx` (`Person_id` ASC) VISIBLE,
  PRIMARY KEY (`Person_id`),
  CONSTRAINT `fk_Client_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClientRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClientRequest` (
  `id` INT NOT NULL,
  `Client_id` INT NOT NULL,
  `Office_Id` INT NOT NULL,
  `details` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `sla` DATE NOT NULL,
  `resolved` BIT NOT NULL,
  PRIMARY KEY (`id`, `Client_id`, `Office_Id`),
  INDEX `fk_ClientRequest_Client1_idx` (`Client_id` ASC) VISIBLE,
  INDEX `fk_ClientRequest_Office1_idx` (`Office_Id` ASC) VISIBLE,
  CONSTRAINT `fk_ClientRequest_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `mydb`.`Client` (`Person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClientRequest_Office1`
    FOREIGN KEY (`Office_Id`)
    REFERENCES `mydb`.`Office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequestFulfillers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequestFulfillers` (
  `request_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  INDEX `fk_RequestFulfillers_ClientRequest1_idx` (`request_id` ASC) VISIBLE,
  PRIMARY KEY (`Employee_id`),
  CONSTRAINT `fk_RequestFulfillers_ClientRequest1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`ClientRequest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RequestFulfillers_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `mydb`.`Employee` (`Person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
