-- MySQL Script generated by MySQL Workbench
-- Thu 19 Sep 2019 08:09:15 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Person
-- -----------------------------------------------------
-- This schema was created for a stub table
DROP SCHEMA IF EXISTS `Person` ;

-- -----------------------------------------------------
-- Schema Person
--
-- This schema was created for a stub table
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Person` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Region` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Region` (
  `id` INT NOT NULL,
  `regionName` VARCHAR(45) NULL,
  `tax` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 't';


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL,
  `Region_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `cost` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Region1_idx` (`Region_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Region1`
    FOREIGN KEY (`Region_id`)
    REFERENCES `mydb`.`Region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL,
  `Person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_Person1_idx` (`Person_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` INT NOT NULL,
  `Person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Person_idx` (`Person_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Person`
    FOREIGN KEY (`Person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Warehouse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Store` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `Manager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Store_Employee1_idx` (`Manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_Store_Employee1`
    FOREIGN KEY (`Manager_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StoreStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StoreStock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StoreStock` (
  `Store_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `stock` VARCHAR(45) NULL,
  INDEX `fk_StoreStock_Store1_idx` (`Store_id` ASC) VISIBLE,
  PRIMARY KEY (`Store_id`, `Product_id`),
  INDEX `fk_StoreStock_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_StoreStock_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `mydb`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StoreStock_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WarehouseStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WarehouseStock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WarehouseStock` (
  `Warehouse_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `stock` VARCHAR(45) NULL,
  PRIMARY KEY (`Warehouse_id`, `Product_id`),
  INDEX `fk_WarehouseStock_Warehouse1_idx` (`Warehouse_id` ASC) VISIBLE,
  INDEX `fk_WarehouseStock_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_WarehouseStock_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `mydb`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WarehouseStock_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DiscountTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DiscountTypes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DiscountTypes` (
  `id` INT NOT NULL,
  `discountPercent` DOUBLE NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeDiscounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmployeeDiscounts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeDiscounts` (
  `Discount_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  PRIMARY KEY (`Discount_id`, `Employee_id`),
  INDEX `fk_EmployeeDiscounts_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  INDEX `fk_EmployeeDiscounts_Discount1_idx` (`Discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_EmployeeDiscounts_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmployeeDiscounts_Discount1`
    FOREIGN KEY (`Discount_id`)
    REFERENCES `mydb`.`DiscountTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WarehouseShipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WarehouseShipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WarehouseShipment` (
  `id` INT NOT NULL,
  `amount` INT NULL,
  `Product_id` INT NOT NULL,
  `from_Warehouse_id` INT NOT NULL,
  `to_Store_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Product_id`, `from_Warehouse_id`, `to_Store_id`),
  INDEX `fk_WarehouseShipment_Warehouse1_idx` (`from_Warehouse_id` ASC) VISIBLE,
  INDEX `fk_WarehouseShipment_Store1_idx` (`to_Store_id` ASC) VISIBLE,
  INDEX `fk_WarehouseShipment_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_WarehouseShipment_Warehouse1`
    FOREIGN KEY (`from_Warehouse_id`)
    REFERENCES `mydb`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WarehouseShipment_Store1`
    FOREIGN KEY (`to_Store_id`)
    REFERENCES `mydb`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WarehouseShipment_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Purchase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Purchase` (
  `idPurchase` INT NOT NULL,
  `date` DATETIME NULL,
  `Store_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `cost` FLOAT NULL,
  PRIMARY KEY (`idPurchase`, `Store_id`, `Customer_id`, `Product_id`),
  INDEX `fk_Purchase_Store1_idx` (`Store_id` ASC) VISIBLE,
  INDEX `fk_Purchase_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Purchase_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `mydb`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Person` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
